// Browser regression for Stop while the static MP3 request is still loading.
import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {testBackend} from './browser-backend.mjs';
const root=path.resolve(import.meta.dirname,'..'),backend=await testBackend(),server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,name==='/'?'index.html':name.slice(1));if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.mp3':'audio/mpeg'})[path.extname(file)]||'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await backend.attach(context,base);
try{
 await page.goto(base+'auth.html');await page.locator('#login-form button:enabled').waitFor();await page.locator('[name=email]').first().fill('student@example.invalid');await page.locator('[name=password]').first().fill('Only-a-test-password-123');await page.locator('#login-form button').click();await page.locator('#account-panel .account-name').waitFor();await page.goto(base+'#session=W1D4');await page.locator('[data-play]').first().waitFor();
 const audio='**/audio/W1D4-E03-R01.mp3';let release,intercepted;const ready=new Promise(resolve=>intercepted=resolve);await context.route(audio,async route=>{await new Promise(resolve=>{release=resolve;intercepted();});await route.continue().catch(()=>{});});
 await page.locator('[data-play]').first().click();await ready;await page.locator('[data-stop-audio]').first().click();release();await page.waitForFunction(()=>!document.querySelector('[data-play]').disabled);assert.match(await page.locator('.audio-row').first().innerText(),/0 \/ 2 escuchas/);assert.equal(await page.evaluate(()=>speechSynthesis.speaking),false);await context.unroute(audio);console.log('PASS Stop during MP3 load cancels playback without spending a listen or starting TTS');
 for(let play=1;play<=2;play++){await page.locator('[data-play]').first().click();await page.locator('.audio-row').first().getByText(play+' / 2 escuchas',{exact:true}).waitFor();await page.locator('[data-stop-audio]').first().click();}
 await page.waitForFunction(()=>document.querySelector('#account-sync').textContent==='Guardado en servidor');await page.reload();await page.locator('[data-play]').first().waitFor();assert.equal(await page.locator('[data-play]').first().isDisabled(),true);assert.match(await page.locator('.audio-row').first().innerText(),/2 \/ 2 escuchas/);assert.deepEqual(errors,[]);assert.equal(backend.providerCalls,0);console.log('PASS Two successful MP3 plays persist after reload; no provider calls or page exceptions');
}finally{await browser.close();await backend.close();await new Promise(resolve=>server.close(resolve));}
