import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {testBackend,A,T} from './browser-backend.mjs';
import {writing} from './fixtures.mjs';
const root=path.resolve(import.meta.dirname,'..'),backend=await testBackend();
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const name=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));const file=path.resolve(root,name);if(!file.startsWith(root+path.sep))throw Error('Invalid path');const data=await fs.readFile(file);const types={'.html':'text/html','.js':'application/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.pdf':'application/pdf'};res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
const errors=[],checks=[];
const check=name=>{checks.push(name);console.log('PASS '+name);};
async function context(options={}){const c=await browser.newContext({acceptDownloads:true,permissions:['microphone'],...options});await backend.attach(c,base);c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));return c;}
async function login(page,email='student@example.invalid'){
  await page.goto(base+'auth.html');await page.locator('#login-form button:enabled').waitFor();await page.locator('[name=email]').first().fill(email);await page.locator('[name=password]').first().fill('Only-a-test-password-123');await page.locator('#login-form button').click();await page.locator('#account-panel .account-name').waitFor();
}
async function saved(page){await page.waitForFunction(()=>document.querySelector('#account-sync')?.textContent==='Guardado en servidor');}
const seed={responses:{'W1D2-E03-Q01':'Legacy extra writing kept intact.'},completed:{W1D1:true},errors:[{key:'legacy-error',id:'W1D1-E01-Q01',category:'Vocabulary',error:'old personal error',correction:'existing correction',resolved:false,date:'1/10/2026'}],plays:{},checked:{}};
try{
  const recoveryContext=await context(),recoveryPage=await recoveryContext.newPage();
  await recoveryPage.goto(base+'auth.html');await recoveryPage.locator('#login-form button:enabled').waitFor();await recoveryPage.locator('#forgot').click();await recoveryPage.locator('#reset-form [name=email]').fill('student@example.invalid');
  const recoveryRequest=recoveryPage.waitForRequest(r=>r.url().includes('/auth/v1/recover'));await recoveryPage.locator('#reset-form button').click();const recoveryURL=new URL((await recoveryRequest).url());assert.equal(recoveryURL.searchParams.get('redirect_to'),base+'auth.html?mode=reset');await recoveryPage.getByText('Si existe una cuenta con ese correo, recibirás el enlace de recuperación.').waitFor();check('Password recovery requests exact safe callback; no credentials in page URL');assert.equal(new URL(recoveryPage.url()).search,'');await recoveryContext.close();
  const c=await context(),page=await c.newPage();const vocab=JSON.parse(await fs.readFile(path.join(root,'data/vocabulary.json'),'utf8'));
  await page.goto(base+'auth.html');await page.evaluate(({seed,vocab,writing})=>{
    localStorage.setItem('aptis-b2-performance-v1',JSON.stringify(seed));
    localStorage.setItem('aptis-b2-vocabulary-v1',JSON.stringify({schemaVersion:1,units:{[vocab]:{status:'Learning',mistakes:2,lapses:2,repetitions:0,dueAt:1,lastCorrect:false}}}));
    localStorage.setItem('aptis-b2-ai-feedback-v1',JSON.stringify({schemaVersion:1,items:{'W1D2-E03-Q01':{exerciseId:'W1D2-E03-Q01',kind:'writing',timestamp:'2026-10-01T10:00:00Z',sourceHash:'a'.repeat(64),feedback:writing,model:'legacy'}}}));
  },{seed,vocab:vocab.units[0].id,writing});
  const raw=await page.evaluate(()=>['aptis-b2-performance-v1','aptis-b2-vocabulary-v1','aptis-b2-ai-feedback-v1'].map(k=>localStorage.getItem(k)));
  await login(page);await page.locator('[data-import-legacy]').waitFor();assert.equal(backend.providerCalls,0);check('Login uses SDK and protected role; no background AI');
  await page.locator('[data-import-legacy]').click();await page.getByText(/Importación verificada:/).waitFor();assert.deepEqual(await page.evaluate(()=>['aptis-b2-performance-v1','aptis-b2-vocabulary-v1','aptis-b2-ai-feedback-v1'].map(k=>localStorage.getItem(k))),raw);check('Three legacy stores imported with original bytes intact');
  await page.goto(base+'#session=W1D1');const answer=page.locator('[data-response="W1D1-E02-Q01"]');await answer.fill('I can help on Saturday mornings because I am free then.');await answer.blur();await saved(page);check('Writing persisted in PostgreSQL');
  await page.locator('[data-ai-correct="W1D1-E02-Q01"]').click();await page.locator('[data-ai-panel="W1D1-E02-Q01"] .ai-result').waitFor();assert.equal(backend.providerCalls,1);check('Authenticated UI → Worker → test provider → persisted feedback');
  await page.locator('[data-ai-panel="W1D1-E02-Q01"] [data-ai-error]').first().check();await page.locator('[data-ai-save="W1D1-E02-Q01"]').click();await saved(page);check('Selected AI error saved to Error Tracker');
  const c2=await context(),page2=await c2.newPage();await login(page2);await page2.goto(base+'#session=W1D1');await page2.locator('[data-response="W1D1-E02-Q01"]').waitFor();assert.equal(await page2.locator('[data-response="W1D1-E02-Q01"]').inputValue(),'I can help on Saturday mornings because I am free then.');check('Second device recovers Writing and IA');
  await c.route(backend.project+'/**',r=>r.abort());await answer.fill('Device A offline variant.');await page.waitForFunction(()=>document.querySelector('#account-sync').textContent==='Pendiente de sincronizar');
  await page2.locator('[data-response="W1D1-E02-Q01"]').fill('Device B version saved on server.');await page2.locator('[data-response="W1D1-E02-Q01"]').blur();await saved(page2);
  await c.unroute(backend.project+'/**');await backend.attach(c,base);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.getByText('Hay otra versión guardada desde otro dispositivo').waitFor();assert.match(await page.locator('.conflict-card').innerText(),/Device A offline variant/);assert.match(await page.locator('.conflict-card').innerText(),/Device B version saved/);await page.locator('[data-conflict="answer:W1D1-E02-Q01"][data-choice="local"]').click();await saved(page);check('Two-device conflict shows and retains both versions');
  await page.goto(base+'#session=W1D1');await c.route(backend.project+'/**',r=>r.abort());await page.locator('[data-response="W1D1-E02-Q01"]').fill('Offline text survives reload.');await page.waitForFunction(()=>document.querySelector('#account-sync').textContent==='Pendiente de sincronizar');await c.unroute(backend.project+'/**');await backend.attach(c,base);await page.reload();await page.locator('[data-response="W1D1-E02-Q01"]').waitFor();await saved(page);assert.equal(await page.locator('[data-response="W1D1-E02-Q01"]').inputValue(),'Offline text survives reload.');check('Offline queue survives reload and reconnects');
  await page.goto(base+'#session=W1D3');await page.locator('[data-record-start="W1D3-E03-Q02"]').waitFor();await page.locator('[data-record-start="W1D3-E03-Q02"]').click();await page.waitForTimeout(1600);await page.locator('[data-record-stop="W1D3-E03-Q02"]').click();await page.locator('[data-record-status="W1D3-E03-Q02"]').filter({hasText:'Audio guardado en servidor'}).waitFor({timeout:15000});assert.equal(backend.objects.size,2);check('MediaRecorder original and analysis WAV uploaded privately');
  await page.locator('[data-ai-target="W1D3-E03-Q02"]').selectOption('1');await page.locator('[data-ai-correct="W1D3-E03-Q02"]').click();await page.locator('[data-ai-panel="W1D3-E03-Q02"] .ai-result').waitFor();assert.equal(backend.providerCalls,2);check('Speaking uses stored exact audio and persists test feedback');
  await page.locator('[data-timer="45"]').first().click();await page.locator('#floating-timer').waitFor();await page.locator('[data-stop-timer]').click();check('Speaking timers retained');
  await page.goto(base+'#session=W1D4');await page.locator('[data-play]').first().waitFor();await page.locator('[data-play]').first().click();await page.locator('[data-stop-audio]').click();await page.locator('[data-play]').first().click();await page.locator('[data-stop-audio]').click();assert.equal(await page.locator('[data-play]').first().isDisabled(),true);await saved(page);check('Listening two plays persist and original controls work');
  await page.goto(base+'#vocabulary-lab');await page.locator('[data-vocab-start]').first().waitFor();await page.locator('[data-vocab-start]').first().click();await page.locator('[data-vocab-choice]').first().waitFor();await page.locator('[data-vocab-choice]').first().click();await saved(page);check('Vocabulary Lab repetition logic persists');
  for(const hash of ['diagnostic','mocks','books','book=writing','book=speaking','book=vocabulary','pdfs','tracker','mock=1&block=A','mock=1&block=B','mock=1&block=C']){await page.goto(base+'#'+hash);await page.locator('#app .card, #app .exercise-card, #app .page-head').first().waitFor();assert.ok((await page.locator('#app').innerText()).length>100);}check('Diagnostic, mocks, books, PDFs and tracker navigation');
  await page.goto(base+'#dashboard');await page.locator('[data-full-export]').waitFor();const download=page.waitForEvent('download');await page.locator('[data-full-export]').click();const backup=JSON.parse(await fs.readFile(await (await download).path(),'utf8'));assert.ok(backup.state.responses['W1D1-E02-Q01']);assert.ok(backup.vocabulary.units);assert.equal(backup.serverFeedback.length,3);check('Complete export includes server feedback, vocabulary and reviews');
  const beforeTeacher=backend.providerCalls;await page.locator('[data-logout]').click();await page.waitForURL(base+'auth.html');await login(page,'teacher@example.invalid');await page.locator('#teacher-detail [data-review-form="W1D1-E02-Q01"]').waitFor();assert.equal(await page.locator('[data-import-legacy]').count(),0);assert.equal(await page.locator('[data-response]').count(),0);assert.equal(backend.providerCalls,beforeTeacher);check('Teacher dashboard reads assigned data without AI calls or editable answers');
  await page.locator('[data-private-audio]').first().click();await page.locator('#teacher-detail audio:not([hidden])').first().waitFor();check('Assigned teacher receives short-lived signed audio');
  const review=page.locator('[data-review-form="W1D1-E02-Q01"]');await review.locator('textarea').fill('Mucho mejor. <img src=x onerror=alert(1)>');await review.locator('button').click();await review.locator('.review-message').filter({hasText:'Comentario guardado'}).waitFor();assert.equal(await page.locator('#teacher-detail img').count(),0);check('Teacher review stored as escaped text');
  await page.locator('[data-logout]').click();await page.waitForURL(base+'auth.html');await login(page);await page.goto(base+'#session=W1D1');await page.getByText('Mucho mejor. <img src=x onerror=alert(1)>',{exact:true}).waitFor();await page.locator('[data-complete="W1D1"]').first().click();await saved(page);await page.goto(base+'#session=W8D4');await page.locator('[data-complete="W8D4"]').first().waitFor();check('Student sees optional review and can access W8 autonomously');
  const mobile=await context({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),mp=await mobile.newPage();await login(mp);await mp.goto(base+'#session=W1D1');await mp.locator('[data-response="W1D1-E02-Q01"]').waitFor();await mp.locator('#menu-toggle').click();assert.equal(await mp.locator('.sidebar').evaluate(el=>el.classList.contains('open')),true);await mp.locator('#mobile-backdrop').click();assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await mp.screenshot({path:path.join(root,'docs/v2-mobile.png'),fullPage:true});check('Mobile login, Writing, navigation and viewport');
  await page.screenshot({path:path.join(root,'docs/v2-student.png'),fullPage:true});
  assert.deepEqual(errors,[]);check('No page exceptions in both roles and mobile');
  await fs.writeFile(path.join(root,'docs/v2-browser-results.json'),JSON.stringify({mode:'Local PostgreSQL + SDK + Worker with isolated Auth/Storage HTTP adapter and synthetic test provider. Not live Supabase/OpenAI.',checks,providerCalls:backend.providerCalls,pageErrors:errors},null,2)+'\n');
  await c.close();await c2.close();await mobile.close();
}catch(error){for(const c of browser.contexts())for(const p of c.pages())console.log('FAILED PAGE',p.url(),(await p.locator('#app').innerText().catch(()=>p.locator('body').innerText())).slice(-3200));throw error;}
finally{await browser.close();await backend.close();await new Promise(resolve=>server.close(resolve));}
