import fs from 'node:fs';
const root=new URL('../',import.meta.url);
// Original practice, independently authored. Sentence arrays express the unique logical order.
const p2=[
['The repaired bicycle','reference',[
 'My neighbour offered me a bicycle that had been unused for several years.',
 'Its tyres were flat, so I took it to a repair shop near my office.',
 'The mechanic there discovered that the brakes also needed replacing.',
 'That extra work made the repair more expensive than I had expected.',
 'Rather than pay the full amount immediately, I asked whether I could spread the cost.',
 'He agreed to two payments, which meant I could collect the bike that afternoon.'],
 ['Its refers to the bicycle introduced in the opening sentence.','The mechanic there refers to the repair shop.','That extra work refers to replacing the brakes.','The full amount refers to the unexpectedly expensive repair.','He refers to the mechanic, answering the request about payment.']],
['A quieter library','cohesion',[
 'Our local library recently received several complaints about noise.',
 'Most of them concerned group meetings held beside the study desks.',
 'To keep those meetings without disturbing readers, the manager proposed using an empty room upstairs.',
 'The room had previously been used for storage and was full of boxes.',
 'Volunteers cleared these out during the following weekend.',
 'With the space finally available, the first upstairs meeting took place on Monday.'],
 ['Them refers to the complaints.','Those meetings refers to the group meetings.','The room refers to the proposed upstairs room.','These refers to the boxes.','The cleared space allows the meeting to take place.']],
['An unexpected journey','chronology',[
 'I arrived at the station expecting to catch the last train home.',
 'A notice on the departure board said that it had been cancelled.',
 'After reading it, I went to the information desk to ask about alternatives.',
 'The assistant suggested a replacement bus leaving from outside the main entrance.',
 'When I reached that entrance, a driver was already checking passengers onto the bus.',
 'I showed him my train ticket and found one of the few seats still free.'],
 ['It refers to the last train.','Reading it refers to the cancellation notice.','The assistant answers the question at the information desk.','That entrance refers to the main entrance just mentioned.','Him refers to the bus driver.']],
['The missing parcel','reference',[
 'A parcel I had ordered was marked as delivered, although nothing had arrived at my door.',
 'I contacted the delivery company and asked where the driver had left it.',
 'They sent me a photograph showing a blue front door.',
 'Mine is green, so the picture confirmed that the address had been confused.',
 'Armed with this evidence, I asked the company to contact the driver again.',
 'He returned an hour later with the parcel and an apology.'],
 ['It refers to the missing parcel.','They refers to the delivery company contacted.','Mine contrasts the writer’s door with the photographed blue door.','This evidence refers to the mismatching door colour.','He refers to the driver whom the company contacted again.']],
['A community garden','cohesion',[
 'Residents in our building decided to turn an unused courtyard into a garden.',
 'Before buying any plants, we asked an expert to examine the ground.',
 'Her report warned that the soil was unsuitable for growing vegetables.',
 'Because of this problem, we chose raised beds filled with fresh compost instead.',
 'The wooden frames for these beds were donated by a nearby carpenter.',
 'His contribution left enough money in our budget to buy the compost and seeds.'],
 ['The expert is introduced before her report.','Her report refers to the expert’s examination.','This problem refers to the unsuitable soil.','These beds refers to the raised beds.','His contribution refers to the carpenter’s donated frames.']],
['Learning to present','chronology',[
 'I agreed to give a presentation at work despite having little experience of public speaking.',
 'To prepare for it, I recorded a practice talk on my phone.',
 'Watching the recording, I noticed that I spoke too quickly whenever I felt nervous.',
 'This habit made the important points difficult to follow.',
 'I therefore added short pauses after those points and practised again.',
 'In the second recording, the pauses made my message much clearer.'],
 ['It refers to the presentation.','The recording must have been made before it can be watched.','This habit refers to speaking too quickly.','Therefore introduces a response to the problem; those points refers back.','The second recording follows the revised practice.']],
['The shared office','reference',[
 'Our small business rented a shared office to reduce its costs.',
 'The rent included a meeting room that several businesses could book.',
 'At first, bookings for this room were written on a sheet beside its door.',
 'The sheet disappeared one morning, leaving nobody sure which bookings were valid.',
 'To prevent a similar confusion, the building manager introduced an online calendar.',
 'Since then, everyone has checked the calendar before arranging a meeting.'],
 ['The rent refers to the rented office.','This room refers to the meeting room.','The sheet refers to the booking sheet.','A similar confusion refers to the loss of booking information.','Since then refers to the introduction of the online calendar.']],
['The weekend exhibition','cohesion',[
 'A friend invited me to exhibit some photographs at a small arts centre.',
 'I accepted, but discovered that the centre required every picture to be framed.',
 'Buying frames for all of them would have exceeded my limited budget.',
 'To avoid that expense, I borrowed a set from the photography club.',
 'Unfortunately, two of the borrowed frames were too small for my prints.',
 'I replaced those two prints with smaller ones and completed the display on time.'],
 ['Acceptance follows the invitation.','Them refers to the pictures; framing creates the cost.','That expense refers to buying frames.','Borrowed frames must be introduced before their size problem.','Those two prints refers to the prints that did not fit.']],
['Changing a recipe','reference',[
 'I planned to bake a cake using a recipe my grandmother had given me.',
 'It called for almonds, which one of my guests could not eat.',
 'To make it safe for her, I replaced them with sunflower seeds.',
 'This substitution made the mixture drier than it should have been.',
 'I added a little extra milk to correct that difference.',
 'The adjusted mixture baked well, and my guest asked for the new recipe.'],
 ['It refers to the recipe.','Them refers to almonds and her to the guest.','This substitution refers to sunflower seeds replacing almonds.','That difference refers to the drier mixture.','The adjusted mixture refers to the mixture after adding milk.']],
['A lost membership card','chronology',[
 'I realised that my swimming-pool membership card was missing when I reached reception.',
 'The receptionist offered to look up my details without it.',
 'Her search showed that my membership had actually expired the previous week.',
 'Until that moment, I had assumed the annual payment was automatic.',
 'Once she explained that it was not, I paid for another year at the desk.',
 'She then issued a replacement card with the new expiry date.'],
 ['It refers to the missing card.','Her search follows the offer to look up details.','That moment refers to discovering the expired membership.','The explanation corrects the assumption about automatic payment.','The new expiry date results from the payment for another year.']],
['The museum survey','cohesion',[
 'The town museum asked visitors how it could improve its exhibitions.',
 'Many respondents said the written descriptions were difficult to understand.',
 'In response to these comments, staff tested shorter descriptions with a school group.',
 'The pupils understood the new versions but wanted more information about everyday life.',
 'Their suggestion led the museum to add examples of how ordinary people used the objects.',
 'These examples are now displayed beside the shorter descriptions.'],
 ['Respondents answers the museum’s question.','These comments refers to difficulty understanding descriptions.','The new versions refers to shorter descriptions tested with pupils.','Their suggestion refers to the pupils’ request about everyday life.','These examples refers to the newly added everyday uses.']],
['A walking route','chronology',[
 'We set off along a coastal path that we had never used before.',
 'After about an hour, we reached a gate with a warning about unstable ground ahead.',
 'Rather than ignore the warning, we consulted the map for another route.',
 'It showed a narrow lane running inland to the village where we wanted to finish.',
 'The lane was longer than the coastal path, but its surface was safe.',
 'We followed it and arrived later than planned, relieved to have avoided the dangerous section.'],
 ['The gate is encountered during the walk.','The warning must be seen before an alternative is sought.','It refers to the map.','The lane refers to the inland route identified on the map.','It now refers to the lane that was followed.']],
['A language exchange','reference',[
 'I joined a language exchange to improve my Spanish conversation.',
 'The organiser paired me with a student who wanted to practise English.',
 'We agreed to divide each meeting equally between the two languages.',
 'This arrangement worked until we started discussing subjects that I found difficult in Spanish.',
 'To help with those subjects, my partner suggested preparing a few useful expressions beforehand.',
 'Using her suggestion, I felt more confident and kept to our original arrangement.'],
 ['The organiser belongs to the exchange introduced.','We refers to the writer and the assigned partner.','This arrangement refers to dividing meeting time equally.','Those subjects refers to difficult discussion subjects.','Her suggestion refers to preparing useful expressions.']],
['The café queue','cohesion',[
 'Customers at the café where I work often complained about the long lunchtime queue.',
 'Our manager observed it for a week to discover where the delays occurred.',
 'She noticed that people choosing sandwiches prevented others from paying for drinks.',
 'To separate these two groups, she moved the sandwiches to a different counter.',
 'The new counter needed another member of staff during the busiest hour.',
 'Although this increased staffing costs, customers were served faster and complaints decreased.'],
 ['It refers to the lunchtime queue.','She refers to the observing manager.','These two groups refers to sandwich buyers and drink buyers.','The new counter refers to the separate sandwich counter.','This refers to employing another staff member.']],
['Restoring an old film','chronology',[
 'An archive discovered a damaged film showing our town nearly a century ago.',
 'Before it could be shown to the public, specialists had to repair the fragile material.',
 'They then produced a digital copy from the repaired film.',
 'Unlike the original, this copy could be viewed repeatedly without causing further damage.',
 'The archive used it to organise a screening for local residents.',
 'Several people at that event recognised buildings which no longer exist.'],
 ['It refers to the damaged film.','They refers to the specialists and then follows repairing.','This copy refers to the digital copy.','It refers to the safe digital copy used for screening.','That event refers to the screening.']],
['The volunteer rota','reference',[
 'Our animal shelter needed a more reliable way to organise weekend volunteers.',
 'Previously, each volunteer had sent their availability in a separate message.',
 'Keeping track of these messages took so long that some shifts were left unfilled.',
 'To solve the problem, a volunteer created a shared online rota.',
 'It allowed everyone to see which shifts still needed help.',
 'As a result, those gaps were filled sooner and the animals received more regular care.'],
 ['Previously introduces the former system being replaced.','These messages refers to separate availability messages.','The problem refers to unfilled shifts caused by tracking messages.','It refers to the shared rota.','Those gaps refers to shifts still needing help.']],
];
// Each opinion includes qualifications which distinguish plausible competing speakers.
const p3=[
['Working from home',[
 ['Anna',"Working at home saves my daily journey, but I miss exchanging ideas without arranging a call. I work better when somebody can question my thinking immediately. One quiet day at home would be useful for reports; spending the entire week there would leave me feeling cut off. I would choose a mixture, with most days in the office."],
 ['Ben',"I expected to enjoy the freedom, yet my workday has become longer. Messages arrive in the evening and I feel obliged to answer because my computer is always nearby. The lack of travel is helpful, but it has not compensated for losing a clear finishing time. I would return to the office if I could."],
 ['Cara',"My job involves checking figures, so interruptions are costly. At home I can finish a difficult calculation before speaking to anyone. I was worried about feeling lonely, but regular calls have been enough. I deliberately shut down at five and leave the room. I see little reason to go back to our noisy office."],
 ['Dan',"I manage a team whose work can mostly be done anywhere. Remote working could help colleagues with caring responsibilities, although some new staff still need face-to-face guidance. Before making it permanent, I would compare results over several months. A policy based only on whether people enjoy it would overlook the purpose of the business."]],
 [['Prefers a combination while keeping more time with colleagues','A','qualification','One quiet day at home; most days in the office'],['Finds it harder to separate work from personal time','B','inference','Messages arrive in the evening; losing a clear finishing time'],['Does concentrated tasks more efficiently away from the office','C','opinion','Interruptions are costly; finish a difficult calculation'],['Wants evidence of performance before a lasting decision','D','qualification','Compare results over several months'],['Expected isolation to be a problem but found a solution','C','inference','Worried about feeling lonely; regular calls have been enough'],['Values spontaneous discussion with other people','A','opinion','Question my thinking immediately'],['Acknowledges that remote work will not suit every employee equally','D','qualification','Caring responsibilities; new staff need face-to-face guidance']]],
['Public transport',[
 ['Anna',"I use the bus every day and usually arrive on time. The fares are reasonable, especially with a monthly pass. My frustration is information: when something does go wrong, the app still shows the original timetable. Knowing whether a bus is actually coming would matter more to me than a small reduction in the price."],
 ['Ben',"The railway is convenient for my office, but taking my children anywhere by train can cost more than driving. I understand that maintenance has to be paid for. Even so, family tickets ought to make occasional trips affordable. I would travel by rail much more at weekends if the total fare were less discouraging."],
 ['Cara',"I used to think an extra bus route would persuade me to leave the car. Now that there is one near my house, I have discovered the real problem: it stops running before my evening shift ends. A service that cannot bring me home is only half a solution. Its frequency during the afternoon is already fine."],
 ['Dan',"Although a new underground line would be impressive, improving existing buses should come first. Small changes to junctions could prevent delays and benefit many routes at once. Building the line might still make sense later, once those changes have been tried. Spending the whole budget on a single project now seems premature."]],
 [['Needs services at a different time rather than more frequent daytime departures','C','qualification','Stops running before my evening shift ends'],['Would choose trains more often if group travel cost less','B','inference','Family tickets; travel by rail more at weekends'],['Prioritises reliable updates over cheaper fares','A','opinion','Knowing whether a bus is actually coming'],['Supports a major project only after simpler improvements','D','qualification','Building the line might still make sense later'],['Changed their explanation for relying on a car','C','inference','Used to think an extra route; discovered the real problem'],['Accepts that the system has expenses but questions the price for families','B','qualification','Maintenance has to be paid for; family tickets'],['Suggests a change that would improve several services together','D','inference','Junctions; benefit many routes at once']]],
['Learning online',[
 ['Anna',"Recorded lessons fit around my changing work shifts. I often stop a video to try a calculation, then replay the explanation if I get stuck. A live class would give me quicker answers, but I would miss too many sessions. Being able to control when and how quickly I study is the main reason I continue."],
 ['Ben',"I registered for an online course because the subject interested me. Without a fixed meeting time, however, I kept postponing the work. The content was excellent; my problem was getting started. I now attend a weekly class where the teacher expects me to participate. That small obligation has made a considerable difference."],
 ['Cara',"Our team uses online courses for basic training, and they are convenient. I would not use them alone for practical skills, though. Seeing someone perform a task on screen is not the same as having them watch you attempt it. Combining an introductory video with supervised practice would give us the best of both approaches."],
 ['Dan',"I live far from any college offering my subject. Online study has opened a door that was previously closed, but the discussions have been unexpectedly valuable too. Students in other countries challenge assumptions I had never questioned. I originally enrolled for the qualification; I now appreciate the different perspectives at least as much."]],
 [['Needs other people’s expectations to maintain a study routine','B','inference','Teacher expects me to participate'],['Values being able to revisit explanations at their own pace','A','opinion','Stop a video; replay the explanation'],['Believes screen-based teaching should be supplemented for hands-on work','C','qualification','Introductory video with supervised practice'],['Gained an unanticipated benefit from other learners','D','inference','Discussions have been unexpectedly valuable'],['Was satisfied with teaching material despite failing to make progress','B','qualification','Content was excellent; problem was getting started'],['Would find scheduled lessons difficult to attend consistently','A','inference','Changing work shifts; miss too many sessions'],['Previously lacked a nearby opportunity to study the subject','D','inference','Far from any college offering my subject']]],
['Visiting museums',[
 ['Anna',"I enjoy finding out how ordinary people lived, rather than admiring famous possessions. A simple kitchen tool can interest me if its label explains what someone did with it. Digital screens sometimes help, but I would rather have a clear story than another button to press. The size of a collection is not what makes a visit memorable."],
 ['Ben',"Taking my son to museums has changed what I look for. We need room to pause, sit down and talk about what we have seen. An exhibition can be fascinating and still feel exhausting if there is no place to rest. I am happy to pay for a visit that considers this; free admission alone does not persuade me."],
 ['Cara',"I used to rush through every gallery to feel I had seen everything. Now I choose one section and spend an hour there. Learning a few things properly is more satisfying than collecting a list of objects I have passed. I sometimes return for another section, although travelling a long distance would make that approach less practical."],
 ['Dan',"A museum should protect its objects, but that does not require visitors to remain passive. A good workshop lets people explore a technique without touching valuable originals. Such activities can make a difficult subject accessible. I support them as long as they explain the collection, rather than turning the museum into an unrelated entertainment centre."]],
 [['Prefers depth of understanding to covering the whole collection','C','opinion','Choose one section; learning a few things properly'],['Judges facilities for taking breaks as part of a good visit','B','opinion','No place to rest; room to pause'],['Accepts interactive activities when they serve an educational purpose','D','qualification','As long as they explain the collection'],['Values explanations of everyday use more than impressive objects','A','opinion','Simple kitchen tool; clear story'],['Recognises a limitation to making repeated visits','C','qualification','Travelling a long distance'],['Would pay for a comfortable experience rather than choose solely by price','B','inference','Happy to pay; free admission alone'],['Does not equate technology with an interesting exhibition','A','inference','Clear story than another button']]],
['Shopping locally',[
 ['Anna',"The small shops near my home remember what I like and give useful advice. I cannot buy everything there, because their range is limited. For specialist items I still order online. Supporting local businesses matters to me, but pretending they can meet every need would not help them understand what customers actually want."],
 ['Ben',"I used to buy groceries online to save time. After several deliveries with unwanted replacements, I began visiting a shop again. Choosing the food myself takes longer but avoids surprises when I cook. I might use delivery during a particularly busy week, provided I could reject substitutions before the order arrived."],
 ['Cara',"A campaign urged us to shop locally, but our village store closes before I finish work. I would gladly use it if it stayed open later even one evening a week. Asking residents to change their habits without offering realistic access seems unfair. Lower prices would be welcome, but they would not solve my problem."],
 ['Dan',"I run a bookshop and know that we cannot match every online discount. Instead, we organise events and help readers discover unfamiliar writers. These services take time, so I hope visitors who enjoy them will occasionally buy a book. I am not asking people to avoid the internet; I want them to recognise what their spending supports."]],
 [['Requires better opening hours before changing where they shop','C','qualification','Closes before I finish work'],['Appreciates personal service while accepting a restricted selection','A','qualification','Useful advice; range is limited'],['Returned to in-person shopping after unreliable product choices','B','inference','Unwanted replacements; choosing food myself'],['Explains how purchases sustain benefits beyond the products','D','inference','Events; recognise what spending supports'],['Might resume delivery if a specific condition were met','B','qualification','Could reject substitutions before the order arrived'],['Believes cheaper goods alone would not remove the main obstacle','C','inference','Lower prices would not solve my problem'],['Tries to compete through expertise rather than price','D','opinion','Cannot match discounts; discover unfamiliar writers']]],
['Exercise habits',[
 ['Anna',"I train with friends twice a week. On days when I feel tired, knowing they are waiting gets me out of the house. The exercise itself would be much the same alone, but I doubt I would do it regularly. We do not compete over speed; keeping the appointment is more useful to me than improving a personal record."],
 ['Ben',"The gym has everything I need, yet getting there uses time I cannot spare. Short sessions at home have been easier to maintain. I miss some equipment, but an ideal workout that never happens is less useful than a simple one I actually do. I would reconsider the gym if one opened closer to work."],
 ['Cara',"Walking used to seem too gentle to count as exercise. Since I started climbing the hill near my flat, I have changed my mind. The effort is real, and being outdoors helps me relax afterwards. I am less interested in measuring steps than in how I feel. Bad weather occasionally keeps me in, but that is a small drawback."],
 ['Dan',"After an injury I had to stop following the routine I found online. A professional helped me adapt it to what my body could manage. General advice can encourage people to start, but it should not replace individual guidance when something hurts. My progress is slower now, although I am more confident that it will last."]],
 [['Depends on a social commitment to remain consistent','A','inference','Knowing they are waiting'],['Favours a manageable routine over an impractical ideal','B','opinion','Simple one I actually do'],['Revised an earlier view about the value of a mild-looking activity','C','inference','Too gentle; changed my mind'],['Recommends tailored help when physical problems arise','D','qualification','Individual guidance when something hurts'],['Accepts less rapid improvement for a more sustainable approach','D','qualification','Slower now; confident it will last'],['Would consider changing location if travelling became easier','B','qualification','If one opened closer to work'],['Cares more about well-being than numerical targets','C','opinion','Less interested in measuring steps']]],
['Planning holidays',[
 ['Anna',"I book accommodation well ahead because arriving somewhere without a bed would worry me. Once that is settled, I leave the days open. A timetable of attractions makes a holiday feel like work. I might reserve a particularly popular museum, but I prefer discovering most things as I go along."],
 ['Ben',"Last year I tried choosing restaurants and activities at the last moment. We wasted hours comparing options and disagreed about what to do. This year everyone will suggest a few priorities before we leave. I do not want a minute-by-minute plan, just enough agreement to avoid spending our holiday making the same decisions repeatedly."],
 ['Cara',"A tour made me nervous because I assumed it would be rigid. In fact, our guide changed the schedule when the weather turned bad and offered different walks for different abilities. That flexibility persuaded me to book another. I would not choose any organised trip automatically, though; the group size and approach still matter."],
 ['Dan',"Travelling outside the main holiday season often makes places quieter and more affordable. I enjoy that, but people should check what remains open. An empty beach is attractive; arriving to find every café closed is less convenient. I recommend the quieter months to independent travellers who are comfortable making a few compromises."]],
 [['Secures the overnight essentials but avoids organising every day','A','qualification','Accommodation ahead; days open'],['Wants advance agreement to reduce repeated group decisions','B','inference','Suggest priorities; same decisions repeatedly'],['Had a negative expectation of organised travel that proved inaccurate','C','inference','Assumed rigid; guide changed schedule'],['Recommends a cheaper period with a warning about reduced services','D','qualification','Affordable; check what remains open'],['Would make an exception for an attraction needing advance booking','A','qualification','Reserve a particularly popular museum'],['Supports planning without wanting a detailed timetable','B','qualification','Not a minute-by-minute plan'],['Would assess particular tours despite a good earlier experience','C','qualification','Group size and approach still matter']]],
['Choosing news sources',[
 ['Anna',"I check several reports when a story is important. Small differences in the facts can show what still needs confirming. This takes longer than reading a headline, but I would rather wait than repeat something misleading. For ordinary local events one reliable source is usually enough; I do not compare everything."],
 ['Ben',"Constant news alerts made it difficult to concentrate. I now read a summary once in the evening and have switched off most notifications. I am still interested in events, but knowing about each development immediately rarely changes what I can do. An urgent local warning is the exception, so I keep those alerts enabled."],
 ['Cara',"I like podcasts because an interview can reveal how a decision was reached. Hearing the reasoning matters more than simply learning the outcome. However, a confident voice can sound convincing without providing evidence. I look for programmes that challenge their guests and publish links, rather than ones that merely offer a pleasant conversation."],
 ['Dan',"My students often share news through short social-media clips. Banning those platforms would probably make them ignore my advice. Instead, I ask them to trace a claim back to its original source. Clips can introduce a useful issue, but understanding what has been left out requires reading beyond them."]],
 [['Compares accounts for major stories but does not do so for every item','A','qualification','Important story; do not compare everything'],['Limits frequent updates without abandoning an interest in events','B','qualification','Still interested; once in the evening'],['Values explanations of the process behind an outcome','C','opinion','Reveal how a decision was reached'],['Teaches a checking method instead of trying to prohibit a medium','D','inference','Instead; trace a claim'],['Believes reassuring delivery is insufficient proof of reliability','C','inference','Confident voice; without evidence'],['Retains immediate information that could require practical action','B','qualification','Urgent local warning'],['Recognises that brief content can be a starting point rather than a full account','D','qualification','Introduce a useful issue; left out']]],
['Learning to cook',[
 ['Anna',"I follow recipes closely when making a dish for the first time. Once I understand the method, I adjust flavours to suit the people eating it. Experimenting before I know the basics tends to waste ingredients. The recipe gives me a dependable starting point rather than a rule I must follow forever."],
 ['Ben',"My parents cooked without measuring much, so I assumed everyone could learn by watching. Trying to bake alone showed me otherwise: small changes in amounts affected the result. I now weigh ingredients carefully for cakes, although I still make soup by taste. Precision matters for some tasks more than for others."],
 ['Cara',"A cookery class taught useful techniques, but the equipment was very different from my tiny kitchen. I struggled to repeat the dishes at home. What helped was choosing recipes using the tools I already had. I might take another class if it focused on everyday cooking in ordinary homes rather than professional facilities."],
 ['Dan',"I cook with my teenage daughter on Sundays. Finishing dinner takes longer than doing it myself, and the kitchen is rarely tidy. Nevertheless, she is becoming confident about preparing food independently. I judge the session by what she learns, not by whether we produce a perfect meal at exactly the planned time."]],
 [['Treats instructions as an initial support before making personal changes','A','qualification','Starting point; adjust flavours'],['Learned that exact quantities matter differently across dishes','B','inference','Weigh for cakes; soup by taste'],['Had difficulty transferring formal training to their own circumstances','C','inference','Equipment different; struggled at home'],['Accepts slower work in exchange for another person gaining a skill','D','qualification','Takes longer; preparing independently'],['Would choose future tuition with a more practical setting','C','qualification','Ordinary homes rather than professional facilities'],['Avoids early experimentation to limit waste','A','inference','Before basics; waste ingredients'],['Places learning ahead of a flawless immediate result','D','opinion','What she learns; not a perfect meal']]],
['Protecting green spaces',[
 ['Anna',"The park near my home is most valuable as a quiet place to sit. I am not opposed to events, but holding them every weekend would remove that benefit. A few each summer could help fund maintenance. The council should decide how often to hold them by considering regular users as well as ticket buyers."],
 ['Ben',"An unused area behind our school could become a garden. Some people want expensive landscaping immediately, but I favour starting with a few beds cared for by pupils. If interest continues, we can expand. A modest project that people maintain seems more promising than a beautiful space they soon neglect."],
 ['Cara',"I support protecting local wildlife, yet closing every path through the woods could weaken that support. People care more about places they can experience. Marked routes away from sensitive areas would allow access while reducing disturbance. Restrictions during the nesting season may still be necessary, provided their purpose is explained."],
 ['Dan',"Volunteers do excellent work cleaning the riverbank, but they should not be expected to replace proper rubbish collection. Without regular council support, the same waste soon returns. Community action can draw attention to the issue and improve things temporarily. A lasting solution also requires the public services to fulfil their responsibilities."]],
 [['Allows occasional commercial use while protecting everyday tranquillity','A','qualification','A few each summer; quiet place'],['Wants a small maintainable beginning before investing further','B','opinion','Start with a few beds; if interest continues'],['Believes controlled access can strengthen public concern for nature','C','inference','Care more about places they can experience'],['Sees voluntary effort as useful but insufficient for a permanent solution','D','qualification','Temporarily; public services'],['Would permit temporary restrictions if the reason were clear','C','qualification','Nesting season; purpose explained'],['Thinks long-term care matters more than impressive initial appearance','B','inference','Maintain; beautiful space soon neglect'],['Wants decisions to account for people who do not attend paid events','A','inference','Regular users as well as ticket buyers']]],
];
const cats={reference:'reference',chronology:'chronology',cohesion:'cohesion'};
const data={schemaVersion:1,provenance:'original practice',notice:'Práctica original independiente; no son preguntas oficiales del British Council.',
 part2:p2.map(([topic,category,texts,hints],n)=>({id:`RL-P2-${String(n+1).padStart(2,'0')}`,topic,first:texts[0],order:['A','B','C','D','E'],sentences:texts.slice(1).map((text,i)=>({id:'ABCDE'[i],text,category:cats[category],explanation:hints[i],evidence:text}))})),
 part3:p3.map(([topic,people,statements],n)=>({id:`RL-P3-${String(n+1).padStart(2,'0')}`,topic,people:people.map(([name,text],i)=>({id:'ABCD'[i],name,text})),statements:statements.map(([text,answer,category,evidence],i)=>({id:String(i+1),text,answer,category,evidence,explanation:`${people['ABCD'.indexOf(answer)][0]} expresa esta idea: ${evidence}.`}))}))};
fs.writeFileSync(new URL('data/reading-lab.json',root),JSON.stringify(data,null,2)+'\n');
console.log(`Original Reading Lab: ${data.part2.length} P2, ${data.part3.length} P3.`);
