import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const root = path.resolve(import.meta.dirname, '..');
const read = name => fs.readFileSync(path.join(root, name));
const baseline = JSON.parse(read('docs/v2-content-baseline.json').toString().replace(/^\uFEFF/, ''));
for (const [name, hash] of Object.entries(baseline.hashes).filter(([name])=>name!=='audio/manifest.json')) assert.equal(crypto.createHash('sha256').update(read(name)).digest('hex'), hash, name);
const course = JSON.parse(read('data/course.json'));
const ids = course.exercises.flatMap(ex => ex.questions.map(q => q.id));
assert.equal(ids.length, 972); assert.equal(new Set(ids).size, 972);
assert.equal(course.exercises.length, 201); assert.equal(course.pdfs.length, 16);
assert.equal(JSON.parse(read('data/vocabulary.json')).units.length, 306);
console.log(`V2 integrity: ${Object.keys(baseline.hashes).length-1} original academic files match; 972 question IDs; 201 exercises; 16 PDFs; 306 vocabulary units. Audio manifest extended separately.`);
