import {escapeHTML as esc} from './accounts.js';
export const categories={cohesion:'Cohesión',reference:'Referencia',chronology:'Cronología',opinion:'Opinión',inference:'Inferencia',qualification:'Matiz y condiciones'};
let data,rows={},save=null,active=null,load;
const attached=new WeakSet();
export function configureReading(snapshot={},onSave=null){rows=snapshot;save=onSave;active=null;}
export function updateReadingSnapshot(snapshot){rows=snapshot;}
export function readingStats(values){
 const result={part2:{attempts:0,correct:0,incorrect:0},part3:{attempts:0,correct:0,incorrect:0},errors:{}};
 for(const value of Object.values(values||{})){const p=result[value.part===2?'part2':'part3'];for(const k of ['attempts','correct','incorrect'])p[k]+=Number(value[k]||0);for(const [k,v]of Object.entries(value.errors||{}))result.errors[k]=(result.errors[k]||0)+v;}
 for(const p of [result.part2,result.part3])p.accuracy=p.correct+p.incorrect?Math.round(p.correct/(p.correct+p.incorrect)*100):null;
 return result;
}
export function scoreReading(task,answers){
 const p2=!!task.order,items=p2?task.order.map((id,i)=>({answer:id,selected:answers[i],...task.sentences.find(s=>s.id===id)})):task.statements.map(s=>({...s,selected:answers[s.id]}));
 return {items:items.map(x=>({...x,correct:x.selected===x.answer})),correct:items.filter(x=>x.selected===x.answer).length,incorrect:items.filter(x=>x.selected!==x.answer).length};
}
function summaryHTML(){const s=readingStats(rows);return `<div class="stats-grid lab-stats">${[['Part 2 · orden',s.part2],['Part 3 · opiniones',s.part3]].map(([label,p])=>`<div class="stat-card"><div class="stat-label">${label}</div><div class="stat-value">${p.accuracy===null?'—':p.accuracy+'%'}</div><p>${p.attempts} intentos · ${p.correct} respuestas correctas · ${p.incorrect} por revisar</p></div>`).join('')}<div class="stat-card"><div class="stat-label">Errores frecuentes</div>${Object.entries(s.errors).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k,n])=>`<p>${esc(categories[k])} · ${n}</p>`).join('')||'<p>Todavía no hay errores registrados.</p>'}</div></div>`;}
function home(){return `<section class="reading-lab"><header class="hero"><div><p class="eyebrow">PRÁCTICA OPCIONAL · READING</p><h1 class="page-title">Reading Lab</h1><p class="page-subtitle">Ordena ideas y comprende opiniones. Practica Part 2 y Part 3 a tu ritmo, fuera de las 32 sesiones.</p></div><div class="hero-side">${data.part2.length} P2 · ${data.part3.length} P3</div></header>${summaryHTML()}<section class="card lab-start"><h2>Elige tu práctica</h2><label>Parte<select id="reading-part"><option value="mixed">Mixto</option><option value="2">Part 2 · ordenar frases</option><option value="3">Part 3 · relacionar opiniones</option></select></label><div class="lab-mode-actions"><button class="primary-button" data-reading-start="5">5 min · Comenzar</button><button class="secondary-button" data-reading-start="10">10 min · Comenzar</button></div></section><p class="vocab-source-note">${esc(data.notice)} ${save?'Progreso guardado en tu cuenta.':'Práctica guardada en este dispositivo.'} La corrección es automática y el profesor no necesita aprobarla.</p></section>`;}
function taskHTML(task){const result=active.result,p2=!!task.order;
 return `<section class="reading-lab"><div class="vocab-practice-top"><button data-reading-home>Salir al Reading Lab</button><span>${active.index+1} / ${active.queue.length} · <span id="reading-clock" role="timer"></span></span></div><article class="card reading-task" lang="en"><p class="eyebrow">PART ${p2?2:3} · ORIGINAL PRACTICE</p><h1>${esc(task.topic)}</h1><p lang="es">${p2?'La primera frase está fijada. Ordena las otras cinco usando los botones Subir y Bajar.':'Relaciona cada afirmación con una persona. Puedes elegir a una persona varias veces.'}</p>${p2?`<p class="reading-fixed"><strong>1.</strong> ${esc(task.first)}</p><ol class="reading-order" start="2">${active.answers.map((id,i)=>{const sentence=task.sentences.find(s=>s.id===id);return `<li><span>${esc(sentence.text)}</span><div class="reading-move"><button data-reading-move="${i}" data-direction="-1" ${i===0||result?'disabled':''} aria-label="Subir frase ${i+2}">↑ <span lang="es">Subir</span></button><button data-reading-move="${i}" data-direction="1" ${i===4||result?'disabled':''} aria-label="Bajar frase ${i+2}">↓ <span lang="es">Bajar</span></button></div></li>`;}).join('')}</ol>`:`<div class="reading-people">${task.people.map(p=>`<section class="reading-person"><h2>${esc(p.id)} · ${esc(p.name)}</h2><p>${esc(p.text)}</p></section>`).join('')}</div><div class="reading-statements">${task.statements.map(s=>`<label>${esc(s.id)}. ${esc(s.text)}<select data-reading-answer="${esc(s.id)}" aria-label="Persona para afirmación ${esc(s.id)}" ${result?'disabled':''}><option value="">Choose a person</option>${task.people.map(p=>`<option value="${esc(p.id)}" ${active.answers[s.id]===p.id?'selected':''}>${esc(p.id)} · ${esc(p.name)}</option>`).join('')}</select></label>`).join('')}</div>`}
 ${result?`<section class="reading-feedback" lang="es" aria-live="polite"><h2>${result.correct} / ${result.correct+result.incorrect} correctas</h2>${result.items.map((item,i)=>`<div class="vocab-feedback ${item.correct?'good':'needs-work'}"><strong>${item.correct?'✓ Correcto':'✕ Revisa'} · ${p2?'Posición '+(i+2):'Afirmación '+(i+1)}</strong><p>Tu respuesta: ${esc(item.selected||'Sin respuesta')} · Correcta: ${esc(item.answer)}</p><p lang="${p2?'en':'es'}">${esc(p2?item.text:item.explanation)}</p><p lang="en">${p2?esc(item.explanation):'Evidence: '+esc(item.evidence)}</p><small>Tipo: ${esc(categories[item.category])}</small></div>`).join('')}<button class="primary-button" data-reading-next>${active.index+1===active.queue.length?'Ver resultado':'Siguiente ejercicio'}</button></section>`:`<p id="reading-message" role="status" lang="es"></p><button class="primary-button" data-reading-check lang="es">Comprobar respuestas</button>`}</article></section>`;
}
function clock(){const el=document.querySelector('#reading-clock');if(!el||!active)return;const sec=Math.max(0,Math.ceil((active.ends-Date.now())/1000));el.textContent=sec?`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`:'Tiempo de práctica terminado · puedes acabar el ejercicio';}
async function draw(root){if(active&&active.index>=active.queue.length){active=null;root.innerHTML=`<div class="v2-banner" role="status">Práctica terminada. Tu resultado está guardado; puedes continuar el curso.</div>`+home();}else root.innerHTML=active?taskHTML(active.queue[active.index]):home();clock();}
export async function renderReadingLab(root){
 if(!data){root.innerHTML='<section class="card" role="status">Cargando Reading Lab…</section>';try{load ||= fetch('./data/reading-lab.json').then(r=>{if(!r.ok)throw Error();return r.json();}).catch(e=>{load=null;throw e;});data=await load;}catch{root.innerHTML='<section class="card">No se pudo cargar la práctica. Comprueba tu conexión y vuelve a abrir Reading Lab.</section>';return;}}
 if(location.hash!=='#reading-lab')return;
 if(!attached.has(root)){attached.add(root);root.addEventListener('change',e=>{const id=e.target.dataset.readingAnswer;if(id&&active&&!active.result)active.answers[id]=e.target.value;});root.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-reading-home')){active=null;draw(root);}
 if(b.dataset.readingStart){const part=root.querySelector('#reading-part').value,minutes=Number(b.dataset.readingStart);let tasks=part==='2'?data.part2:part==='3'?data.part3:data.part2.flatMap((p,i)=>i<data.part3.length?[p,data.part3[i]]:[p]);tasks=[...tasks].sort((a,b)=>(rows[a.id]?.attempts||0)-(rows[b.id]?.attempts||0));active={queue:tasks.slice(0,minutes===5?2:4),index:0,ends:Date.now()+minutes*60000};prepare();draw(root);}
 if(b.dataset.readingMove!=null&&active&&!active.result){const i=Number(b.dataset.readingMove),j=i+Number(b.dataset.direction);if(j<0||j>=5)return;[active.answers[i],active.answers[j]]=[active.answers[j],active.answers[i]];draw(root);const buttons=[...root.querySelectorAll(`[data-reading-move="${j}"]`)];(buttons.find(x=>x.dataset.direction===b.dataset.direction&&!x.disabled)||buttons.find(x=>!x.disabled))?.focus();}
 if(b.hasAttribute('data-reading-check')&&active&&!active.result){const task=active.queue[active.index];if(!task.order&&task.statements.some(s=>!active.answers[s.id])){root.querySelector('#reading-message').textContent='Elige una persona para cada afirmación antes de comprobar.';return;}const result=scoreReading(task,active.answers),previous=rows[task.id]||{part:task.order?2:3,attempts:0,correct:0,incorrect:0,errors:{}};const errors={...previous.errors};for(const item of result.items)if(!item.correct)errors[item.category]=(errors[item.category]||0)+1;const value={part:previous.part,attempts:previous.attempts+1,correct:previous.correct+result.correct,incorrect:previous.incorrect+result.incorrect,errors,lastAt:Date.now()};rows[task.id]=value;if(save)save(task.id,value);else try{localStorage.setItem('aptis-reading-lab-v1',JSON.stringify(rows));}catch{}active.result=result;draw(root);}
 if(b.hasAttribute('data-reading-next')&&active){active.index++;prepare();draw(root);}
 });setInterval(clock,1000);}
 await draw(root);
}
function prepare(){if(!active||active.index>=active.queue.length)return;const task=active.queue[active.index];active.result=null;active.answers=task.order?[task.order[2],task.order[0],task.order[4],task.order[1],task.order[3]]:{};}
